# Generated by Django 2.0.1 on 2018-02-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=255)),
                ('path', models.ImageField(blank=True, null=True, upload_to='artwork', verbose_name='path')),
                ('txid', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
